#!/usr/bin/env bash

CONTAINER_NAME="chatmi"
PORT="8181"

if [ $# -gt 0 ]; then
    if [ "$1" == "attach" ]; then
        docker build -t $CONTAINER_NAME .
        docker stop $CONTAINER_NAME
        docker rm $CONTAINER_NAME
        docker run -p $PORT:$PORT -d --name="$CONTAINER_NAME" $CONTAINER_NAME
        docker logs -f $(docker ps -aqf "name=$CONTAINER_NAME")
    elif [ "$1" == "run" ]; then
        docker build -t $CONTAINER_NAME .
        docker run -p $PORT:$PORT -d --name="$CONTAINER_NAME" $CONTAINER_NAME
    elif [ "$1" == "clean" ]; then
        docker stop $CONTAINER_NAME
        docker rm $CONTAINER_NAME
    fi
else
docker build -t $CONTAINER_NAME .
fi
